//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;
use alohomora::{bbox::BBox, policy::NoPolicy, AlohomoraType};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "admin")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: BBox<i32, NoPolicy>,
    pub name: BBox<String, NoPolicy>,
    pub public_key: BBox<String, NoPolicy>,
    #[sea_orm(column_type = "Text")]
    pub private_key: BBox<String, NoPolicy>,
    pub password: BBox<String, NoPolicy>,
    pub created_at: BBox<DateTime, NoPolicy>,
    pub updated_at: BBox<DateTime, NoPolicy>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::admin_session::Entity")]
    AdminSession,
}

impl Related<super::admin_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
