//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;
use alohomora::bbox::BBox;
use portfolio_policies::FakePolicy;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "candidate")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: BBox<i32, FakePolicy>,
    pub name: Option<BBox<String, FakePolicy>>,
    pub surname: Option<BBox<String, FakePolicy>>,
    pub birth_surname: Option<BBox<String, FakePolicy>>,
    pub birthplace: Option<BBox<String, FakePolicy>>,
    pub birthdate: Option<BBox<String, FakePolicy>>,
    pub address: Option<BBox<String, FakePolicy>>,
    pub letter_address: Option<BBox<String, FakePolicy>>,
    pub telephone: Option<BBox<String, FakePolicy>>,
    pub citizenship: Option<BBox<String, FakePolicy>>,
    pub email: Option<BBox<String, FakePolicy>>,
    pub sex: Option<BBox<String, FakePolicy>>,
    pub personal_identification_number: BBox<String, FakePolicy>,
    pub school_name: Option<BBox<String, FakePolicy>>,
    pub health_insurance: Option<BBox<String, FakePolicy>>,
    pub grades_json: Option<BBox<String, FakePolicy>>,
    pub first_school: Option<BBox<String, FakePolicy>>,
    pub second_school: Option<BBox<String, FakePolicy>>,
    pub test_language: Option<BBox<String, FakePolicy>>,
    pub encrypted_by_id: Option<BBox<i32, FakePolicy>>,
    pub created_at: BBox<DateTime, FakePolicy>,
    pub updated_at: BBox<DateTime, FakePolicy>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::application::Entity")]
    Application,
    #[sea_orm(has_many = "super::parent::Entity")]
    Parent,
}

impl Related<super::application::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Application.def()
    }
}

impl Related<super::parent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Parent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
