//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;
use alohomora::bbox::BBox;
use portfolio_policies::data::CandidateDataPolicy;
use portfolio_policies::FakePolicy;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "parent")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: BBox<i32, CandidateDataPolicy>,
    pub candidate_id: BBox<i32, CandidateDataPolicy>,
    pub name: Option<BBox<String, CandidateDataPolicy>>,
    pub surname: Option<BBox<String, CandidateDataPolicy>>,
    pub telephone: Option<BBox<String, CandidateDataPolicy>>,
    pub email: Option<BBox<String, CandidateDataPolicy>>,
    pub created_at: BBox<DateTime, FakePolicy>,
    pub updated_at: BBox<DateTime, FakePolicy>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::candidate::Entity",
        from = "Column::CandidateId",
        to = "super::candidate::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Candidate,
}

impl Related<super::candidate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Candidate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
